export const BUNDLED_QUESTIONS = [
  {
    id: 'design-url-shortener',
    title: 'Design a URL Shortener',
    description: 'Design a service like bit.ly that takes long URLs and generates short, unique aliases that redirect to the original URL.',
    functionalRequirements: 'Users submit a long URL and receive a shortened URL. Shortened URLs redirect to the original. Custom aliases supported. URLs can expire. Analytics on click counts.',
    nonFunctionalRequirements: 'Handle 100M+ URLs. Low latency redirects (<100ms). High availability (99.9%). Read-heavy (100:1 read-to-write). Shortened URLs should be as short as possible.',
    expectedComponents: ['API Gateway', 'URL Shortening Service', 'Database (key-value or SQL)', 'Cache (for hot URLs)', 'Load Balancer', 'Analytics Service'],
    evaluationCriteria: ['URL encoding strategy (base62, hashing, counter)', 'Read path optimization with caching', 'Collision handling', 'Horizontal scalability of the write path', 'Cache eviction strategy for hot URLs', 'Database choice justification'],
    difficulty: 'easy' as const,
    tags: ['Storage', 'Caching', 'API Design'],
  },
  {
    id: 'design-chat-system',
    title: 'Design a Chat System',
    description: 'Design a real-time messaging platform supporting 1-on-1 and group conversations, similar to WhatsApp or Slack.',
    functionalRequirements: '1-on-1 messaging. Group chats (up to 500 members). Online/offline presence indicators. Read receipts. Push notifications for offline users. Message history and search.',
    nonFunctionalRequirements: 'Real-time delivery (<500ms). Support 50M daily active users. Message persistence. Eventual consistency for group messages. End-to-end encryption option.',
    expectedComponents: ['WebSocket Gateway', 'Chat Service', 'Message Queue', 'Database (messages)', 'Presence Service', 'Push Notification Service', 'Cache', 'Load Balancer'],
    evaluationCriteria: ['WebSocket vs long-polling choice', 'Message ordering guarantees', 'Fan-out strategy for group messages', 'Offline message delivery', 'Message storage and retrieval at scale', 'Presence system design'],
    difficulty: 'medium' as const,
    tags: ['Messaging', 'Real-Time'],
  },
  {
    id: 'design-notification-system',
    title: 'Design a Notification System',
    description: 'Design a scalable notification platform that delivers push, SMS, and email notifications with user preferences and rate limiting.',
    functionalRequirements: 'Push notifications (iOS/Android), SMS, and email. Rate limiting per user. Notification preferences and opt-out. Template-based notifications. Scheduled notifications. Priority levels.',
    nonFunctionalRequirements: 'Deliver 10M+ notifications per day. Soft real-time (<30s for push). High availability. At-least-once delivery. Deduplication. Audit trail.',
    expectedComponents: ['API Gateway', 'Notification Service', 'Message Queue', 'Priority Queue', 'Rate Limiter', 'Template Engine', 'Push Provider (FCM/APNS)', 'SMS Provider', 'Email Provider', 'User Preferences Store'],
    evaluationCriteria: ['Multi-channel delivery architecture', 'Rate limiting strategy', 'Priority handling under load', 'Retry and dead-letter queue design', 'Template rendering pipeline', 'User preference lookup efficiency'],
    difficulty: 'medium' as const,
    tags: ['Messaging', 'Distributed'],
  },
  {
    id: 'design-rate-limiter',
    title: 'Design a Rate Limiter',
    description: 'Design a distributed rate limiting service that protects APIs from abuse while being accurate under high concurrency.',
    functionalRequirements: 'Limit requests per user/IP/API key. Multiple rules (per second, minute, hour). Return appropriate HTTP headers. Configurable limits per endpoint. Whitelist/blacklist support.',
    nonFunctionalRequirements: 'Sub-millisecond latency overhead. Distributed across multiple servers. Accurate counting under concurrency. Graceful degradation if rate limiter fails.',
    expectedComponents: ['Rate Limiter Service', 'Redis/Cache (counters)', 'Rules Configuration Store', 'Load Balancer', 'Monitoring/Alerting'],
    evaluationCriteria: ['Algorithm choice (token bucket, sliding window, fixed window, leaky bucket)', 'Distributed synchronization strategy', 'Race condition handling', 'Failure mode (fail-open vs fail-closed)', 'Multi-tier rate limiting (local + global)', 'Header communication design'],
    difficulty: 'medium' as const,
    tags: ['API Design', 'Distributed', 'Caching'],
  },
  {
    id: 'design-news-feed',
    title: 'Design a News Feed System',
    description: 'Design a social media news feed like Facebook or Twitter that shows relevant posts from followed users with ranking.',
    functionalRequirements: 'Users post content. Feed shows posts from followed users. Ranking by relevance and recency. Support text, images, video. Like, comment, share. Infinite scroll pagination.',
    nonFunctionalRequirements: 'Feed generation within 2 seconds. Support 500M+ users. Handle celebrity users (millions of followers). Eventual consistency acceptable. 99.9% availability.',
    expectedComponents: ['Post Service', 'Feed Generation Service', 'Fan-out Service', 'Cache (feed cache)', 'Database (posts, social graph)', 'CDN (media)', 'Ranking Service', 'Message Queue'],
    evaluationCriteria: ['Fan-out on write vs fan-out on read tradeoff', 'Celebrity/hot user problem handling', 'Feed ranking algorithm approach', 'Cache invalidation strategy', 'Social graph storage and traversal', 'Media delivery optimization'],
    difficulty: 'hard' as const,
    tags: ['Social', 'Caching', 'Distributed'],
  },
  {
    id: 'design-web-crawler',
    title: 'Design a Web Crawler',
    description: 'Design a distributed web crawler that can crawl billions of pages while being polite, fault-tolerant, and efficient.',
    functionalRequirements: 'Crawl pages starting from seed URLs. Extract and follow links. Store page content for indexing. Respect robots.txt. Handle different content types. URL deduplication.',
    nonFunctionalRequirements: 'Crawl 1B pages per month. Politeness (rate limit per domain). Fault-tolerant. Detect and avoid crawler traps. Prioritize important pages. Handle dynamic JS-rendered pages.',
    expectedComponents: ['URL Frontier (priority queue)', 'Fetcher Service', 'DNS Resolver', 'Content Parser', 'URL Deduplicator (Bloom filter)', 'Robots.txt Cache', 'Storage (raw pages)', 'Link Extractor', 'Scheduler'],
    evaluationCriteria: ['URL frontier design and prioritization', 'Politeness implementation (per-host delays)', 'Deduplication strategy (URL and content level)', 'Handling of dynamic content', 'Fault tolerance and checkpoint/restart', 'Distributed coordination of crawl workers'],
    difficulty: 'hard' as const,
    tags: ['Distributed', 'Storage'],
  },
  {
    id: 'design-key-value-store',
    title: 'Design a Distributed Key-Value Store',
    description: 'Design a distributed key-value store like DynamoDB or Redis Cluster with tunable consistency and partition tolerance.',
    functionalRequirements: 'Put(key, value) and get(key) operations. Configurable replication factor. TTL support. Range queries on keys. Batch operations.',
    nonFunctionalRequirements: 'Tunable consistency (strong vs eventual). Automatic partitioning and rebalancing. Handle network partitions. Sub-10ms reads. Horizontal scalability to petabytes.',
    expectedComponents: ['Coordinator Node', 'Storage Nodes', 'Consistent Hashing Ring', 'Replication Manager', 'Gossip Protocol', 'Write-Ahead Log', 'Compaction Service'],
    evaluationCriteria: ['Partitioning strategy (consistent hashing)', 'Replication and conflict resolution', 'Consistency model (quorum reads/writes)', 'Failure detection and recovery', 'Data compaction and storage engine choice', 'Cluster membership and rebalancing'],
    difficulty: 'hard' as const,
    tags: ['Storage', 'Distributed'],
  },
  {
    id: 'design-search-autocomplete',
    title: 'Design Search Autocomplete',
    description: 'Design a typeahead/autocomplete system that returns top suggestions as users type, like Google search suggestions.',
    functionalRequirements: 'Return top 5 suggestions as user types. Suggestions based on popularity/frequency. Personalized suggestions. Multilingual support. Filter inappropriate content.',
    nonFunctionalRequirements: 'Response time under 100ms. Handle 10K QPS. Suggestions update based on trending data. Graceful degradation. Low storage for trie structures.',
    expectedComponents: ['Trie Service', 'Data Collection Service', 'Aggregation Pipeline', 'Cache (hot prefixes)', 'Load Balancer', 'Analytics/Trending Service'],
    evaluationCriteria: ['Data structure choice (trie, prefix hash)', 'Ranking strategy for suggestions', 'Real-time vs batch update of frequencies', 'Handling of trending/breaking queries', 'Storage optimization (trie compression)', 'Serving layer latency optimization'],
    difficulty: 'medium' as const,
    tags: ['Search', 'Caching'],
  },
  {
    id: 'design-pastebin',
    title: 'Design Pastebin',
    description: 'Design a service like Pastebin where users can store and share plain text snippets via unique URLs.',
    functionalRequirements: 'Users paste text and get a unique URL. Optional expiration time. Syntax highlighting. Private vs public pastes. View count tracking. User accounts optional.',
    nonFunctionalRequirements: 'Handle 5M new pastes per day. Fast reads. Content limited to 10MB per paste. 99.9% availability. Data retention policies.',
    expectedComponents: ['API Gateway', 'Paste Service', 'Object Storage (paste content)', 'Metadata Database', 'Cache', 'CDN', 'Cleanup/Expiration Service'],
    evaluationCriteria: ['Separation of metadata vs content storage', 'URL generation strategy', 'Read optimization with CDN and cache', 'Storage cost management for large volumes', 'Expiration handling (lazy vs active deletion)', 'Abuse prevention'],
    difficulty: 'easy' as const,
    tags: ['Storage', 'API Design'],
  },
  {
    id: 'design-twitter',
    title: 'Design Twitter',
    description: 'Design a microblogging platform with tweets, follows, likes, retweets, and a home timeline.',
    functionalRequirements: 'Post tweets (280 chars + media). Follow/unfollow users. Home timeline. Like and retweet. Hashtags and search. Trending topics. Direct messages.',
    nonFunctionalRequirements: '300M+ monthly active users. Timeline generation < 1s. Handle viral tweets (millions of engagements). Eventual consistency acceptable. High write throughput during events.',
    expectedComponents: ['Tweet Service', 'Timeline Service', 'Fan-out Service', 'Social Graph Service', 'Search Service', 'Trending Service', 'Media Service', 'Cache', 'Message Queue', 'CDN'],
    evaluationCriteria: ['Timeline generation (push vs pull vs hybrid)', 'Celebrity follower problem', 'Tweet storage and partitioning', 'Search indexing strategy', 'Trending algorithm', 'Media upload and delivery pipeline'],
    difficulty: 'hard' as const,
    tags: ['Social', 'Real-Time', 'Search'],
  },
  {
    id: 'design-youtube',
    title: 'Design YouTube',
    description: 'Design a video sharing platform supporting upload, transcoding, streaming, and recommendations.',
    functionalRequirements: 'Upload videos. Transcode to multiple resolutions. Stream with adaptive bitrate. Comments, likes, subscriptions. Search. Recommendations. Live streaming.',
    nonFunctionalRequirements: '500 hours of video uploaded per minute. Billions of daily views. Global low-latency streaming. 99.99% availability for playback. Cost-efficient storage.',
    expectedComponents: ['Upload Service', 'Transcoding Pipeline', 'CDN', 'Video Metadata DB', 'Object Storage', 'Streaming Service', 'Recommendation Engine', 'Search Service', 'Message Queue', 'Thumbnail Generator'],
    evaluationCriteria: ['Video processing pipeline design', 'Adaptive bitrate streaming (HLS/DASH)', 'CDN strategy for global delivery', 'Storage tiering (hot/warm/cold)', 'Transcoding parallelization', 'Recommendation system architecture'],
    difficulty: 'hard' as const,
    tags: ['Streaming', 'Media', 'Storage'],
  },
  {
    id: 'design-uber',
    title: 'Design Uber/Ride Sharing',
    description: 'Design a ride-sharing platform that matches riders with nearby drivers in real-time.',
    functionalRequirements: 'Rider requests a ride. Match with nearest available driver. Real-time location tracking. ETA calculation. Fare estimation. Payment processing. Trip history. Rating system.',
    nonFunctionalRequirements: 'Match within 30 seconds. Handle millions of concurrent rides. Real-time location updates (every 3-5s). 99.99% availability. Consistent fare calculation.',
    expectedComponents: ['Ride Matching Service', 'Location Service', 'Driver Service', 'Trip Service', 'Pricing Service', 'Payment Service', 'Notification Service', 'Map/ETA Service', 'Message Queue', 'Geospatial Database'],
    evaluationCriteria: ['Geospatial indexing for proximity search', 'Real-time location ingestion at scale', 'Matching algorithm efficiency', 'Surge pricing implementation', 'Consistency in payment processing', 'Handling of high-density areas'],
    difficulty: 'hard' as const,
    tags: ['Geospatial', 'Real-Time', 'Payments'],
  },
  {
    id: 'design-dropbox',
    title: 'Design Dropbox/File Storage',
    description: 'Design a cloud file storage and synchronization service supporting multiple devices and collaboration.',
    functionalRequirements: 'Upload/download files. Sync across devices. File versioning. Sharing with permissions. Conflict resolution. Large file support (chunked upload). Folder structure.',
    nonFunctionalRequirements: 'Support files up to 50GB. Sync latency < 5s for small files. Handle millions of concurrent syncs. Minimize bandwidth usage (deduplication, delta sync). 99.9% durability.',
    expectedComponents: ['Client Sync Agent', 'Metadata Service', 'Block Storage', 'Chunking Service', 'Notification Service (change events)', 'Deduplication Service', 'CDN', 'Queue'],
    evaluationCriteria: ['Chunked upload and resume strategy', 'Delta sync (only changed blocks)', 'Conflict resolution for concurrent edits', 'Deduplication across users', 'Metadata vs content separation', 'Notification mechanism for real-time sync'],
    difficulty: 'hard' as const,
    tags: ['Storage', 'Distributed', 'Real-Time'],
  },
  {
    id: 'design-instagram',
    title: 'Design Instagram',
    description: 'Design a photo/video sharing social network with feeds, stories, explore, and direct messaging.',
    functionalRequirements: 'Upload photos/videos. Apply filters. Follow users. News feed. Stories (24h expiry). Explore/discover page. Direct messages. Likes and comments.',
    nonFunctionalRequirements: '1B+ monthly active users. Fast image loading globally. Feed generation < 500ms. High write throughput for uploads. 99.9% availability.',
    expectedComponents: ['Upload Service', 'Image Processing Service', 'CDN', 'Feed Service', 'Story Service', 'Social Graph DB', 'Object Storage', 'Cache', 'Search Service', 'Notification Service'],
    evaluationCriteria: ['Image processing pipeline (resize, filter, format)', 'CDN strategy for global image delivery', 'Feed generation (precomputed vs on-demand)', 'Story expiration mechanism', 'Explore page ranking', 'Storage optimization (different resolutions)'],
    difficulty: 'medium' as const,
    tags: ['Social', 'Media', 'Caching'],
  },
  {
    id: 'design-tinder',
    title: 'Design Tinder/Dating App',
    description: 'Design a location-based dating application with swiping, matching, and messaging.',
    functionalRequirements: 'User profiles with photos. Location-based discovery. Swipe left/right. Mutual match notification. In-app messaging. Preferences filtering (age, distance, gender).',
    nonFunctionalRequirements: 'Recommendations within 100ms. Handle 50M+ users. Real-time match notifications. Location updates as users move. Privacy-preserving location.',
    expectedComponents: ['Recommendation Service', 'Geospatial Index', 'Profile Service', 'Matching Service', 'Chat Service', 'Notification Service', 'Image CDN', 'Cache'],
    evaluationCriteria: ['Geospatial querying for nearby users', 'Recommendation algorithm (avoid showing same profiles)', 'Swipe event processing at scale', 'Mutual match detection efficiency', 'Location privacy considerations', 'Photo serving optimization'],
    difficulty: 'medium' as const,
    tags: ['Geospatial', 'Real-Time', 'Social'],
  },
  {
    id: 'design-ticketmaster',
    title: 'Design Ticketmaster/Event Booking',
    description: 'Design a ticket booking system handling high-concurrency sales events without overselling.',
    functionalRequirements: 'Browse events. Select seats/tickets. Reserve temporarily. Process payment. Issue ticket/confirmation. Waitlist. Refunds. Prevent double-booking.',
    nonFunctionalRequirements: 'Handle flash sales (100K+ concurrent users for one event). No overselling. Payment completion within 30s. 99.99% availability during sales. Fair queuing.',
    expectedComponents: ['Event Catalog Service', 'Inventory Service', 'Reservation Service', 'Payment Service', 'Queue/Waiting Room', 'Notification Service', 'Cache', 'Database (strong consistency)'],
    evaluationCriteria: ['Inventory consistency under high concurrency', 'Reservation timeout and release mechanism', 'Virtual queue/waiting room for flash sales', 'Distributed locking or optimistic concurrency', 'Payment failure handling and rollback', 'Seat map state management'],
    difficulty: 'hard' as const,
    tags: ['E-Commerce', 'Payments', 'Distributed'],
  },
  {
    id: 'design-google-maps',
    title: 'Design Google Maps',
    description: 'Design a mapping service with navigation, real-time traffic, route planning, and location search.',
    functionalRequirements: 'Map rendering at multiple zoom levels. Turn-by-turn navigation. Real-time traffic data. Route calculation (fastest, shortest). Points of interest search. ETA with traffic.',
    nonFunctionalRequirements: 'Route calculation < 2s. Global coverage. Real-time traffic updates. Handle millions of concurrent navigation sessions. Offline map support.',
    expectedComponents: ['Map Tile Service', 'Routing Engine', 'Traffic Data Ingestion', 'Geocoding Service', 'Search Service', 'CDN (map tiles)', 'Location Service', 'Graph Database (road network)'],
    evaluationCriteria: ['Map tile serving and caching strategy', 'Graph-based routing algorithm (Dijkstra, A*)', 'Real-time traffic data integration', 'Road network data structure', 'ETA prediction accuracy', 'Offline support architecture'],
    difficulty: 'hard' as const,
    tags: ['Geospatial', 'Caching', 'Streaming'],
  },
  {
    id: 'design-google-docs',
    title: 'Design Google Docs',
    description: 'Design a real-time collaborative document editing system supporting multiple simultaneous editors.',
    functionalRequirements: 'Create/edit documents. Real-time collaboration (multiple cursors). Version history. Comments and suggestions. Sharing with permissions. Offline editing with sync.',
    nonFunctionalRequirements: 'Real-time sync < 100ms between collaborators. Handle 100+ simultaneous editors. No data loss. Conflict-free merging. 99.9% availability.',
    expectedComponents: ['Document Service', 'Collaboration Engine (OT/CRDT)', 'WebSocket Server', 'Version Store', 'Permission Service', 'Notification Service', 'Object Storage'],
    evaluationCriteria: ['Conflict resolution strategy (OT vs CRDT)', 'Operational transform implementation approach', 'Document state synchronization', 'Cursor and selection broadcasting', 'Version history storage efficiency', 'Offline edit reconciliation'],
    difficulty: 'hard' as const,
    tags: ['Real-Time', 'Distributed'],
  },
  {
    id: 'design-payment-system',
    title: 'Design a Payment System',
    description: 'Design a payment processing system like Stripe handling transactions, refunds, and multi-currency support.',
    functionalRequirements: 'Process credit card payments. Support multiple payment methods. Refunds and chargebacks. Multi-currency. Recurring billing/subscriptions. Webhook notifications. PCI compliance.',
    nonFunctionalRequirements: 'Process 1000+ TPS. Exactly-once payment semantics. 99.999% availability. Strong consistency for balances. Audit trail for all transactions. < 2s payment processing.',
    expectedComponents: ['Payment Gateway', 'Transaction Service', 'Ledger Service', 'Fraud Detection', 'Currency Exchange Service', 'Webhook Service', 'Retry Queue', 'Audit Log', 'Idempotency Store'],
    evaluationCriteria: ['Idempotency for payment requests', 'Double-entry ledger design', 'Distributed transaction handling', 'Fraud detection integration point', 'Retry and reconciliation strategy', 'PCI-DSS compliance architecture'],
    difficulty: 'hard' as const,
    tags: ['Payments', 'Distributed'],
  },
  {
    id: 'design-amazon',
    title: 'Design Amazon E-commerce',
    description: 'Design the core e-commerce platform: product catalog, cart, checkout, order management, and recommendations.',
    functionalRequirements: 'Product catalog with search. Shopping cart. Checkout flow. Order tracking. Reviews and ratings. Recommendations. Inventory management. Seller portal.',
    nonFunctionalRequirements: 'Handle Black Friday traffic (10x normal). Sub-second search. Strong consistency for inventory. 99.99% availability for checkout. Global deployment.',
    expectedComponents: ['Product Catalog Service', 'Search Service', 'Cart Service', 'Order Service', 'Inventory Service', 'Payment Service', 'Recommendation Engine', 'CDN', 'Cache', 'Message Queue', 'Warehouse Service'],
    evaluationCriteria: ['Inventory reservation and consistency', 'Search indexing and ranking', 'Cart persistence strategy', 'Order state machine design', 'Handling flash sales without overselling', 'Recommendation pipeline architecture'],
    difficulty: 'hard' as const,
    tags: ['E-Commerce', 'Search', 'Payments'],
  },
  {
    id: 'design-netflix',
    title: 'Design Netflix',
    description: 'Design a video streaming platform with content delivery, personalization, and adaptive streaming.',
    functionalRequirements: 'Browse content catalog. Stream video adaptively. Personalized recommendations. Multiple profiles per account. Continue watching. Download for offline. Parental controls.',
    nonFunctionalRequirements: 'Support 200M+ subscribers. Buffer-free streaming globally. 99.99% playback availability. Handle peak evening traffic. Minimize bandwidth costs.',
    expectedComponents: ['Content Catalog Service', 'Streaming Service', 'CDN (multi-tier)', 'Recommendation Engine', 'Encoding Pipeline', 'User Profile Service', 'Playback Service', 'A/B Testing Platform'],
    evaluationCriteria: ['CDN architecture (Open Connect)', 'Adaptive bitrate streaming', 'Content encoding pipeline', 'Recommendation algorithm approach', 'Multi-region failover', 'Personalization at scale'],
    difficulty: 'medium' as const,
    tags: ['Streaming', 'Media', 'Caching'],
  },
  {
    id: 'design-spotify',
    title: 'Design Spotify',
    description: 'Design a music streaming platform with playlists, recommendations, social features, and offline playback.',
    functionalRequirements: 'Stream music on demand. Create/share playlists. Personalized discover weekly. Search by song/artist/album. Offline downloads. Social (follow, collaborative playlists). Podcasts.',
    nonFunctionalRequirements: 'Instant playback start (<200ms). Handle 400M+ users. Low bandwidth adaptive streaming. Fair royalty tracking. 99.9% availability.',
    expectedComponents: ['Audio Streaming Service', 'Content Catalog', 'Recommendation Engine', 'Playlist Service', 'Search Service', 'CDN', 'Royalty Tracking Service', 'Social Graph', 'Offline Sync Service'],
    evaluationCriteria: ['Audio streaming delivery (CDN, P2P)', 'Recommendation and personalization pipeline', 'Royalty calculation accuracy', 'Playlist storage and sharing', 'Search across music metadata', 'Offline download and sync mechanism'],
    difficulty: 'medium' as const,
    tags: ['Streaming', 'Search', 'Media'],
  },
  {
    id: 'design-whatsapp',
    title: 'Design WhatsApp',
    description: 'Design an end-to-end encrypted messaging app supporting text, media, voice/video calls, and groups.',
    functionalRequirements: 'Text messaging. Media sharing (images, video, documents). Voice and video calls. Group chats (up to 1024). End-to-end encryption. Status/stories. Message backup.',
    nonFunctionalRequirements: '2B+ users. Message delivery < 100ms (online users). Support 100B messages/day. Minimal server-side storage (E2E encryption). 99.99% availability.',
    expectedComponents: ['Connection Gateway (WebSocket)', 'Message Routing Service', 'Encryption Key Exchange', 'Media Storage', 'Group Service', 'Presence Service', 'Push Notification Service', 'Backup Service'],
    evaluationCriteria: ['End-to-end encryption implementation (Signal Protocol)', 'Message delivery guarantees', 'Group message fan-out', 'Media upload/download with encryption', 'Connection management at billions scale', 'Offline message queuing'],
    difficulty: 'hard' as const,
    tags: ['Messaging', 'Real-Time', 'Distributed'],
  },
  {
    id: 'design-zoom',
    title: 'Design Zoom/Video Conferencing',
    description: 'Design a video conferencing platform supporting meetings, screen sharing, recording, and breakout rooms.',
    functionalRequirements: 'Video/audio conferencing (up to 1000 participants). Screen sharing. Recording. Chat during meetings. Breakout rooms. Virtual backgrounds. Waiting room. Calendar integration.',
    nonFunctionalRequirements: 'End-to-end latency < 150ms. Adaptive quality based on bandwidth. Support millions of concurrent meetings. 99.99% availability. Global deployment.',
    expectedComponents: ['Signaling Server', 'Media Server (SFU/MCU)', 'TURN/STUN Server', 'Recording Service', 'Chat Service', 'CDN', 'Load Balancer', 'Scheduler Service'],
    evaluationCriteria: ['Media architecture (SFU vs MCU vs mesh)', 'Bandwidth adaptation strategy', 'Server placement for latency optimization', 'Large meeting scalability', 'Recording pipeline design', 'Failover during active meetings'],
    difficulty: 'hard' as const,
    tags: ['Real-Time', 'Streaming', 'Media'],
  },
  {
    id: 'design-airbnb',
    title: 'Design Airbnb',
    description: 'Design a marketplace for short-term rentals with search, booking, payments, and reviews.',
    functionalRequirements: 'List properties with photos/details. Search by location, dates, price, amenities. Book with date availability. Payment processing. Reviews for hosts and guests. Messaging between host and guest.',
    nonFunctionalRequirements: 'Search results < 1s. Handle seasonal spikes. Strong consistency for booking (no double-book). Global availability. Trust and safety features.',
    expectedComponents: ['Search Service', 'Listing Service', 'Booking Service', 'Availability Service', 'Payment Service', 'Review Service', 'Messaging Service', 'Image CDN', 'Geospatial Index', 'Fraud Detection'],
    evaluationCriteria: ['Availability calendar management and consistency', 'Search ranking (location, price, quality)', 'Booking conflict resolution', 'Geospatial search implementation', 'Trust and safety architecture', 'Dynamic pricing support'],
    difficulty: 'medium' as const,
    tags: ['E-Commerce', 'Geospatial', 'Search'],
  },
  {
    id: 'design-slack',
    title: 'Design Slack',
    description: 'Design a team communication platform with channels, threads, integrations, and search.',
    functionalRequirements: 'Workspaces and channels. Real-time messaging. Threads. File sharing. Integrations/bots (webhooks). Search across all messages. Reactions. User presence.',
    nonFunctionalRequirements: 'Real-time delivery (< 200ms). Support 10M+ daily active users. Message search across years of history. Handle bursty traffic (start of workday). 99.9% availability.',
    expectedComponents: ['WebSocket Gateway', 'Channel Service', 'Message Service', 'Search Service (Elasticsearch)', 'File Storage', 'Integration Service', 'Presence Service', 'Notification Service', 'Cache'],
    evaluationCriteria: ['Channel message delivery architecture', 'Search indexing for message history', 'Thread model and notifications', 'Integration/webhook processing', 'Workspace isolation and multi-tenancy', 'Connection management for real-time'],
    difficulty: 'medium' as const,
    tags: ['Messaging', 'Real-Time', 'Search'],
  },
  {
    id: 'design-elasticsearch',
    title: 'Design a Distributed Search Engine',
    description: 'Design a full-text search engine supporting indexing, querying, ranking, and horizontal scaling.',
    functionalRequirements: 'Index documents. Full-text search with relevance ranking. Filter and faceted search. Autocomplete. Aggregations. Near real-time indexing. Schema management.',
    nonFunctionalRequirements: 'Query latency < 50ms at p99. Index billions of documents. Handle 10K QPS. Horizontal scalability. Fault tolerance (node failures).',
    expectedComponents: ['Index Service', 'Query Service', 'Inverted Index Storage', 'Shard Manager', 'Replication Manager', 'Cluster Coordinator', 'Tokenizer/Analyzer Pipeline'],
    evaluationCriteria: ['Inverted index design and storage', 'Sharding strategy for documents', 'Query parsing and execution plan', 'Relevance scoring (TF-IDF, BM25)', 'Near real-time indexing pipeline', 'Cluster coordination and leader election'],
    difficulty: 'hard' as const,
    tags: ['Search', 'Distributed', 'Storage'],
  },
  {
    id: 'design-stock-exchange',
    title: 'Design a Stock Exchange',
    description: 'Design a stock trading platform with order matching, real-time price updates, and transaction processing.',
    functionalRequirements: 'Place buy/sell orders (market, limit). Order matching engine. Real-time price ticker. Portfolio tracking. Transaction history. Market data feed. Pre/post market trading.',
    nonFunctionalRequirements: 'Order matching < 1ms. Handle 100K+ orders per second. Strict ordering (FIFO per price level). Zero data loss. Exactly-once execution. Real-time price dissemination.',
    expectedComponents: ['Order Gateway', 'Matching Engine', 'Order Book', 'Market Data Publisher', 'Settlement Service', 'Risk Management', 'Sequencer', 'Audit Log'],
    evaluationCriteria: ['Order book data structure and matching algorithm', 'Strict ordering guarantees (sequencer)', 'Ultra-low latency architecture', 'Market data fan-out to subscribers', 'Risk checks before order acceptance', 'Fault tolerance without data loss'],
    difficulty: 'hard' as const,
    tags: ['Real-Time', 'Payments', 'Distributed'],
  },
  {
    id: 'design-monitoring-system',
    title: 'Design a Monitoring/Alerting System',
    description: 'Design an infrastructure monitoring system like Datadog that collects metrics, detects anomalies, and triggers alerts.',
    functionalRequirements: 'Collect metrics from services (CPU, memory, custom). Time-series storage. Dashboard visualization. Alert rules and thresholds. Alert routing (PagerDuty, Slack, email). Anomaly detection.',
    nonFunctionalRequirements: 'Ingest millions of metrics per second. Query latency < 1s for dashboards. Alert evaluation < 30s. 30-day retention at full resolution, years at lower resolution. High availability.',
    expectedComponents: ['Agent/Collector', 'Ingestion Pipeline', 'Time-Series Database', 'Query Engine', 'Alert Evaluator', 'Alert Router', 'Dashboard Service', 'Downsampling Service'],
    evaluationCriteria: ['Time-series storage engine design', 'Ingestion pipeline scalability', 'Efficient querying over time ranges', 'Alert evaluation at scale', 'Data downsampling and retention policies', 'Push vs pull collection model'],
    difficulty: 'medium' as const,
    tags: ['Monitoring', 'Streaming', 'Distributed'],
  },
  {
    id: 'design-food-delivery',
    title: 'Design a Food Delivery System',
    description: 'Design a food delivery platform like DoorDash connecting restaurants, customers, and delivery drivers.',
    functionalRequirements: 'Browse restaurants by location. Menu browsing. Cart and checkout. Real-time order tracking. Driver assignment and routing. Restaurant order management. Reviews and ratings.',
    nonFunctionalRequirements: 'Order placement < 3s. Driver matching within 60s. Real-time location updates. Handle meal-time spikes. Delivery ETA accuracy. 99.9% availability.',
    expectedComponents: ['Restaurant Service', 'Order Service', 'Driver Matching Service', 'Location Service', 'Routing/ETA Service', 'Payment Service', 'Notification Service', 'Search Service', 'Geospatial Index'],
    evaluationCriteria: ['Driver matching and dispatch algorithm', 'Real-time location tracking at scale', 'Order state machine (placed → preparing → picked up → delivered)', 'ETA prediction with traffic', 'Handling surge demand during peak hours', 'Restaurant capacity management'],
    difficulty: 'medium' as const,
    tags: ['Geospatial', 'Real-Time', 'E-Commerce'],
  },
];
